### ISSUE TITLE
Update association mapping (MixedReferrers)

### ISSUE THREAD

**Issue by rmsint** [sonata-project/SonataDoctrinePhpcrAdminBundle#106]
Follow up of https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/100#discussion_r3431511
- add MixedReferrers to the [FormContractor](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Builder/FormContractor.php)
- add associations to the [ListBuilder](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Builder/ListBuilder.php#L100)
  - embeds associations in table rows
  - see also the related templates: https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Builder/ListBuilder.php#L132

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
