### ISSUE TITLE
link between frontend and backend

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#116]
- [x] with https://github.com/symfony-cmf/RoutingBundle/pull/273 you can have a link from the edit view of a document to its frontend representation.
- [ ] Provide a link to the frontend in the list view too.
- [ ] provide a sonata link from the frontend in the create toolbar for the mainContent.

**Comment by wouterj** [comment]
*Migrated to CmfSonataPhpcrAdminIntegrationBundle: https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle/issues/95*
