### ISSUE TITLE
Audit / Versionning

### ISSUE THREAD

**Issue by rande** [sonata-project/SonataDoctrinePhpcrAdminBundle#12]
Hello,

I just add a support for Audit/Versionning, I have started to add interfaces in the AdminBundle and the implementation in DoctrineORMAdminBundle. I am not sure if the interface can match the PHPCR requirements, can you please have a look the the following comments and provides any comments you might have.

Thanks. 
- https://github.com/sonata-project/SonataAdminBundle/commit/baa6cd0ee9bc9fef43d90eef8dcd621b8817342e
- https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/f3eec647e92a23726f3fe739f97a1a18f993c929

**Comment by INHack20** [comment]
+1 +1 +1

will support versioning of documents?
symfony an alternative to version documents?

**Comment by dbu** [comment]
@INHack20 doctrine phpcr-odm supports versioning. but nobody yet built support for the functionality into sonata admin. maybe this can simply be an admin extension, but probably direct support in sonata admin would allow a better user experience.

versioning is explained at http://doctrine-phpcr-odm.readthedocs.org/en/latest/reference/versioning.html

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
