### ISSUE TITLE
check if getUrlsafeIdentifier function needs url encoding

### ISSUE THREAD

**Issue by sjopet** [sonata-project/SonataDoctrinePhpcrAdminBundle#159]
see [ModelManager](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Model/ModelManager.php#L298)

**Comment by ElectricMaxxx** [comment]
Any input on that question now?

**Comment by dbu** [comment]
i think there would have been a bug report if thats not working. its been like this forever.

**Comment by ElectricMaxxx** [comment]
But we should remove the `TODO`entry from the code then ;-)

**Comment by dbu** [comment]
agreed
