### ISSUE TITLE
Make filter inside list function case insensitive 

### ISSUE THREAD

**Issue by milosnovi** [sonata-project/SonataDoctrinePhpcrAdminBundle#161]
Hi,

currently filtering content, as part of list action, is case sensitive. Is it possible to make it insensitive?

thx

**Comment by ElectricMaxxx** [comment]
@lsmith77  this issue is really old, but is the query builder ready now, can we start implementing this issue?

**Comment by ElectricMaxxx** [comment]
@dbu  same question for you?

**Comment by dbu** [comment]
i have no idea. but it would still be useful to have the behaviour. no blocker however.

**Comment by ElectricMaxxx** [comment]
solved through #424
