### ISSUE TITLE
Use PropertyAccess instead of reflection

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#187]
ModelManager::modelReverseTransform is using reflection instead of PropertyAccess

**Comment by wouterj** [comment]
Is this really wanted? I was about to fix this PR, but I think it does some things differently:

 * SonataDoctrineOrmBundle is using reflection as well, it would be nice to have this all consistent (behaviour expectations)
 * Currently, the value is always set (one way of another). If it's not via setters, public properties or the like, it's using `ReflectionProperty` from Doctrine's metadata. With the PropertyAccessor, there has to be a public property or setter in other to use it.

**Comment by dbu** [comment]
ok, lets opt for consistency then
