### ISSUE TITLE
doctrine_phpcr_odm_tree_manager make possible to show root

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#207]
make it possible to show the root element so that you can also add something to the root.

right now, we only ever show the children of root, and that is inconvenient when you for example have the additionalInfoBlock as you can't just show that container block.

this is probably related to #148

**Comment by wouterj** [comment]
*This issue can be closed with the usage of the new TreeBrowser.*
