### ISSUE TITLE
Overlay editing: remove sonata navigation, fix close button

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#217]
When editing in the overlay, we see all the Sonata navigation elements in the overlay again. Hide those. 
And we should make all "close",  "Save and Return" and so on buttons hide the overlay after successful saving.

**Comment by dbu** [comment]
would be a nice-to-have for 2.0 but not really a blocker imho

**Comment by ElectricMaxxx** [comment]
@dbu  we have got an example in our sandbox admin for that?

**Comment by dbu** [comment]
i found no example. in one of our projects, we have a field for the page
children (for blocks and such):

```php
$formMapper
   ->with('Page structure')
        ->add('structure', 'doctrine_phpcr_odm_tree_manager',
array('mapped' => false, 'root' => $this->getSubject()->getId()))
   ->end()
;
```

this shows a tree of all blocks and things below the page. you can click
on things in that page to open an overlay where you can edit e.g. the block.

**Comment by ElectricMaxxx** [comment]
not really a blocker as you mentioned before, would mean for me: i would skip that one.

**Comment by dbu** [comment]
would be nice, but as nobody did it in the last 4 years, lets close it
