### ISSUE TITLE
Non-existent service doctrine_phpcr.odm.default_document_manager

### ISSUE THREAD

**Issue by rifeman2007** [sonata-project/SonataDoctrinePhpcrAdminBundle#231]
Hi All,

Anyone know about this issue? I am using "sonata-project/doctrine-phpcr-admin-bundle": "1.0.*@dev"

The service "sonata.admin.manager.doctrine_phpcr" has a dependency on a non
-existent service "doctrine_phpcr.odm.default_document_manager".

Thanks in advance.

**Comment by TomArrow** [comment]
Having the same problem. What was your solution?

**Comment by dbu** [comment]
just a wild guess: do you have a doctrine_phpcr entry in your config.yml? and are you changing the default document manager name to something else than "default"?

if @rifeman2007 is still active and remembers what he did, i hope he can tell us what the issue was.

**Comment by timgrob** [comment]
May I ask how the configuration was changed to get it working?

**Comment by dbu** [comment]
this configuration is known to work with the current stable version of phpcr-odm: https://github.com/symfony-cmf/cmf-sandbox/blob/1.3.0/app/config/config.yml#L56-L82

do you have the doctrine_phpcr section as well as doctrine => dbal?

**Comment by timgrob** [comment]
I have both, doctrine_phpcr section as well as doctrine.dbal, in my composer.json.

**Comment by dbu** [comment]
and the doctrine_phpcr section does have an odm subsection?

**Comment by timgrob** [comment]
No, I only had an orm subsection:

"/config.yml"
orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

**Comment by dbu** [comment]
erm. doctrine_phpcr has no orm subsection. are you sure you are not mixing up orm and phpcr-odm?
