### ISSUE TITLE
improve introduction

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#242]
@rmsint said in #103 

This is what I quickly thought to do:
- [ ] an overview page:
  - in the cmf documentation style
  - dependencies + installation + basic configuration
  - main features: list, filter, form, tree
  - links to sonata documents where possible
- [ ] a separate page to explain the phpcr filters (mostly the page as it is now)
- [ ] provide a place (separate page probably) to explain the new, and existing, phpcr form types
  - in one or two sentences explain them on the overview page
- [x] provide a place to explain the tree (separate page probably)

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
