### ISSUE TITLE
Nice UI for Multilanguage Documents

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#26]
Using a language switcher, you can edit all languages of a document: http://symfony.com/doc/master/cmf/tutorials/handling-multilang-documents.html

A cool feature would be to have language tabs to edit all languages without changing the request locale (which also changes the language of the user interface)

**Comment by WouterJ** [comment]
Now we use the SonataTranslationBundle, isn't this issue actually fixed?

**Comment by dbu** [comment]
indeed it is. thanks for going through these old issues, wouter!
