### ISSUE TITLE
Implement support for export

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#260]
implement ModelManager::getDataSourceIterator at https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Model/ModelManager.php#L549
#251 added at least an exception instead of returning null.

until that is done, the only export is the phpcr level export and import, which is the right thing for backups anyways, but not suitable for end users.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
