### ISSUE TITLE
tweak tree children configuration

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#265]
Add a second behaviour to the [phpcrodm tree](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Tree/PhpcrOdmTree.php#L137) that uses DocumentManager::getChildren instead of looking for mappings. 

Orthogonal to that, one could allow to deactivate the allowed children filtering and always allow all. Or provide a blacklist instead of whitelist option for that filter. 

We should factor out those methods into strategy classes rather than just add more methods to the PhpcrOdmTree.php

**Comment by ElectricMaxxx** [comment]
Is that still relevant?

**Comment by dbu** [comment]
definitely not for 2.0

i just close this. there is a ton we could do, but don't have to. so lets get people that need such features do it. and ftr most of that should be done in resource/tree bundles, not here.
