### ISSUE TITLE
Support Versionable Documents

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#27]
expose the API for versioning:
- create new version
- see list of versions
- load old version
- restore content to an old version
- optionally completely delete an old version

To control what is currently published, we should maintain a separate tree. Publishing would copy the selected version from the editing tree to the publication tree. (Looking up a specific label on each request is an expensive overhead and error prone, and could mess up with search.). JCR-based CMS  like magnolia even support copying the jcr subtree from one system to another, to support different servers for editing and publishing.

We probably need to [fix versioned documents children mappings](https://github.com/doctrine/phpcr-odm/pull/574) for this to be fully usable.

**Comment by jordisala1991** [comment]
IMO duplicated of #12, we should unify discussions.

Closing for now. If you think this should be reopened, please consider closing the other one.
