### ISSUE TITLE
Unpublish now

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#314]
have a js button next to the publication end date to set the end date to the current date + time to unpublish a document.

**Comment by ElectricMaxxx** [comment]
Is that still relevant?

**Comment by dbu** [comment]
would be nice ux enhancement, but certainly no 2.0 blocker. removed the milestone.

**Comment by wouterj** [comment]
*This can be closed, I've migrated it to the CmfSonataPhpcrAdminIntegrationBundle: https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle/issues/93 *
