### ISSUE TITLE
publication workflow in the area of the save buttons?

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#315]
As the publish decision is about saving the content and not just one of many sections of the content, the controls would ideally be shown next to the save buttons. we could even replace "Save" with a "Publish" and "Save Draft" resp. "Unpublish" button. (without versioning, saving draft of a published content is not possible, only unpublish)

**Comment by wouterj** [comment]
*This issue can be closed, I've migrated it to the CmfSonataPhpcrAdminIntegrationBundle (where it belongs): https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle/issues/94*
