### ISSUE TITLE
Composer warning: "Package sonata-project/jquery-bundle is abandoned"

### ISSUE THREAD

**Issue by dantleech** [sonata-project/SonataDoctrinePhpcrAdminBundle#318]
Package sonata-project/jquery-bundle is abandoned, you should avoid using it. No replacement was suggested.

--

=> update this bundle to use recent SoantaAdminBundle and update our documentation to point to the sonata doc on how to use the bower.json provided

**Comment by lsmith77** [comment]
see also https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/322

**Comment by wouterj** [comment]
*This issue can be closed, jquery bundle is no longer installed afaik (see also #322)*
