### ISSUE TITLE
Tree style admin instead of list style admin

### ISSUE THREAD

**Issue by RSSchermer** [sonata-project/SonataDoctrinePhpcrAdminBundle#324]
I only just started playing around with the CMF project and I'm really impressed with how little custom code on top of the CMF is needed to make quite a nice custom CMS. One thing I'm was not quite happy with during my experimentation though, is the list-centric backend interface, which does not seem ideally suited for hierarchical content.

A tree view would be much better suited. If I'm not mistaken, currently the only way to get a tree view without defining custom templates and controllers, is to use the dashboard tree block provided with this bundle. This tree is really quite nice, esspecially as it allows reordering of tree nodes. There are some problems with this approach though:
- It's difficult to have multiple trees on seperate pages without resorting to custom templates and controllers. I'd prefer having a separate content tree, menu tree, route tree etc., rather than having them all in one tree.
- If you want to add nodes to a tree, you still end up going through the sonata list style interfaces, complicating the user experience unnecessarily.

I would propose something like `TreeAdmin` and `TreeNodeAdmin`.

`TreeAdmin` would be responsible for a tree view. The tree view could include:
- The tree with a specified root node. This can probably just use the tree block already provided by this bundle.
- A 'Node creation'  side menu, which lists the nodes that can be created for this tree with 'Add new' links.

`TreeAdmin` services can be added to Sonata groups and show up in the Sonata admin list block or in the dashboard side-menu with a 'Tree' link which takes you to the tree view.

`TreeNodeAdmin` would be responsible for the CRUD of nodes for the tree. It takes care of the form, show, delete etc views for a tree node. It could basically be the current phpcr admin class, with the difference that a parent `TreeAdmin` needs to be specified. The views would differ from the sonata list style views in:
- Breadcrumbs include a link to the parent tree view, instead of a list view.
- Buttons like 'Create and return to list' are changed to 'Create and return to tree'.

I'd be willing to look into implementing something like this. If I'd ever end up making a proper CMS with the CMF, this is probably what I would do anyway, but I figured this may be a generic enough problem that there would be upstream interest. Before I get started though, I'm curious as to what sentiments here are for something like this and if perhaps there's better ideas for the implementation than what I came up with above.

One issue I already ran into when playing around with this, is the somewhat 'monolithic' nature of the sonata `Admin` class (and by extension the Phpcr `Admin` class which inherits from it). It includes a lot of cruft relating to list view specifics and it feels a little wrong to extend it for something like `TreeAdmin` or `TreeNodeAdmin`. A lot of logic (e.g. for routing and security) would however be shared. I'd prefer it if there was a base admin class that is view agnostic. It seems that would be a pretty big refactor for the SonataAdminBundle though.

**Comment by dantleech** [comment]
You have chosen a good time to bring this up as we are currently working on replacing/improving the Tree browser. /cc @WouterJ

**Comment by dbu** [comment]
@RSSchermer first of all, hi and welcome!
glad if you want to look into this. @WouterJ started working on this in #321 and the TreeBrowserBundle. best discuss with him to get the current state and bring in your inputs.

about the monolithic admin class: there are now admin extensions too, which can be used to create shared functionality between admins. maybe this could help in this case?

**Comment by RSSchermer** [comment]
hi @dbu, thanks for the kind welcome!

Perhaps I should not have brought the Sonata Admin issue up. It's not a practical issue, I think everything can be implemented just fine by just inheriting from it. It just irks me a little conceptually. A `TreeAdmin` class like I described would share a large chunk of logic with the Sonata `Admin`, let's call it  `ListCRUDAdmin` for a moment. It would need methods like `getRoutes` and `isGranted`. However, it does not need methods like `getListFieldDescriptions` or `getListBuilder`. If `TreeAdmin` was to extend `ListCRUDAdmin` these last methods would also become part of its interface though. This isn't a practical problem, we can just ignore them, but it does feel a little dirty to me. This does not seem like something that extensions would solve, in fact, they seem to suffer from the same issue.

The quick solution would be to define `BaseAdmin` in the SonataAdminBundle as a view agnostic starting point. It provides the basic methods all admins need, like `getCode`,  `getRoutes`, `getBaseControllerName`, but not the list/form/show etc. specific interface. Sonata `Admin` would then extend `BaseAdmin`. This would preserve BC.

My ideal solution would probably leverage traits (I'm not sure what php versions Sonata aims to support, but mixins do seem ideal for this purpose), something like this:

```php
// Defines the shared admin interface, like BaseAdmin described above
interface AdminInterface {...}

abstract class Admin implements AdminInterface {...}

// List specific methods
interface ListAdminInterface extends AdminInterface {...}

// Form specific methods
interface FormAdminInterface extends AdminInterface {...}

// Show specific methods
interface ShowAdminInterface extend AdminInterface {...}

// Etc.

trait ListAdminTrait {...}
trait FormAdminTrait {...}
trait ShowAdminTrait {...}
// Etc.

// This would replace the current Admin class
abstract class ListCRUDAdmin extends Admin implements
    ListAdminInterface,
    FormAdminInterface,
    ShowAdminInterface,
    ...
{
    use ListAdminTrait, FormAdminTrait, ShowAdminTrait, ...;
    ...
}
```

This would increase complexity a little, but it would cut that 2800 line Admin class up into more managable pieces and would allow for more flexible composition. You could do something like this for example:
```php
abstract class SingletonAdmin extends Admin implements FormAdminInterface 
{
    use FormAdminTrait;
    ...
}
```
And use it for managing global settings or something like that.

`TreeAdmin` and `TreeNodeAdmin` could then look something like this:
```php
interface TreeAdminInterface {...}

abstract class TreeAdmin extends Admin implements TreeAdminInterface {...}

interface TreeNodeAdminInterface {...}

abstract class TreeNodeAdmin extends Admin implements
    TreeNodeAdminInterface,
    FormInterface,
    ShowableInterface,
    ...
{
    use FromAdminTrait, ShowAdminTrait, ...;
    ...
}
```
This would be major surgery on the SonataAdminBundle though and you'd probably end up breaking BC, even if you'd wanna keep the current `Admin` class named `Admin` instead of something like `ListCRUDAdmin`.

For now I'll just extend the current Admin class and ignore the interface pollution. If Sonata ever does get a restructure it should be simple enough to adjust the inheritance.

**Comment by dbu** [comment]
radically refactoring SonataAdminBundle would be a really huge undertaking i fear. this would need to be discussed at the SonataAdminBundle repo - i am no maintainer of the base sonata admin.

for the tree things, @WouterJ and @dantleech are currently doing a lot of work that should make things a lot more elegant. can you guys give some input here, point RSSchemer to the right direction of how this is going to look? (maybe a good moment to start with documentation efforts ;-)

**Comment by WouterJ** [comment]
* The tree-centric approach instead of the list approach. I do think that's the way to go too (look at neos for great examples of a tree-centric admin interface). However, the SonataAdminBundle has such deep list-centric roots that you are unable to create a tree-centric admin with it.

   This means we'll have to use other admins and that's exactly the idea we're playing with too. We've decided to improve the SonataAdminBundle support and GUI in the coming CMF 1.3 and see if we can add support for other admins in CMF 1.4. This means we can also look into tree-centric approaches. However, I don't think the CMF should provide admin bundles itself. There are way to much admin interfaces already.

* The current tree is going to be upgraded in CMF 1.3, making it easier to use. I quite like your idea of using a filter to only so some nodes. E.g. for the route admin, only show the route nodes. This could work together with https://github.com/symfony-cmf/ResourceRestBundle/issues/7#issuecomment-73219787

**Comment by RSSchermer** [comment]
@WouterJ Thanks for the input!

I'll hold off on trying to implement something on top of Sonata for the moment then. I did some experimentation and there are definately some issues, mainly:

- The already mentioned inflexibility and focus on lists. While lists are definately important, there has to be an agnostic core that is not concerned with the type of content and it's presentation at all.
- The documentation is lacking. This might actually be the bigger problem. For an admin project like sonata, the developer experience needs to be excellent (otherwise why use an admin project and not just do MVC yourself?). Documentation might be the number one factor.

I agree with @dbu that evolving the sonata admin bundle is a large undertaking and it will probably not reach the ideal situation. I'm actually quite tempted to start a new admin project that takes a documentation driven approach: programming interface, features and configurable options all described first and then implemented to work exactly as described, and nothing more than described. There'd be a major focus on working nicely with hierarchical content.

**Comment by WouterJ** [comment]
(ps, I'm already working hard to fixing Sonata docs, I know it's a huge issue of the Sonata bundles at the moment: https://github.com/sonata-project/SonataAdminBundle/pull/2649)

**Comment by dbu** [comment]
> I'm actually quite tempted to start a new admin project

careful with that one :-) there are a bunch of admins out there. the problem with all of them is not enough resources to make them shine. doing yet another one is not necessarily going to make the situation better... see https://packagist.org/search/?q=admin-bundle

we where kind of wanting to checkout the kunstmaan admin stuff but nobody found time yet. i think we need to find a way to better collaborate one admins (or a few with really different approaches) rather than this gazillion of attempts which are lacking in man-power and documentation.

**Comment by dantleech** [comment]
Last time I checked (over a year ago) the Kunstmann stuff was highly coupled to Kunstmann, as the Sulu stuff is highly coupled to Sulu. NG Admin is interesting. I personally think there is alot of scope for a real admin *framework*, i.e. with an OOP way of describing interfaces (like GTK), where you can generate HTML/JS frontend from an OOP schema. But it is a bucket-load of work.

**Comment by dbu** [comment]
right, https://github.com/marmelab/ng-admin sounds interesting too. with the ResourceBundle, this could reduce the admin to a bit of js configuration...

**Comment by rande** [comment]
When the SonataAdminBundle has been created (~4 years ago), front end technologies were not as mature as today: no angular, no react, etc .... Also, backend developers need to focus on "API first" as applications can now be used by many devices: phones, browsers, TVs, etc ... 

The current drawback of the SonataAdminBundle is that you cannot reuse the code to create an "Admin API" as the code is too linked to the view representation.

I am working on a prototype based on ReactJS to build front end applications. The main idea behind this work is not to force user about how an admin should be: edit, list, search .... Each user will be free to register ``Component`` against ``Route``. Of course the code will use API available on the backend. The main advantage of ReactJS (vs Angular) is that ``Component`` are pretty easy to understand for non JS developers. 

The idea behind the prototype is to check either if the code can be integrated with SonataAdminBundle: you can imagine to have classic CRUD for some entities and having rich experience for others.

**Comment by RSSchermer** [comment]
> I personally think there is alot of scope for a real admin framework, i.e. with an OOP way of describing interfaces (like GTK), where you can generate HTML/JS frontend from an OOP schema.

I'm not 100% sure what you mean by that, but...:

> right, https://github.com/marmelab/ng-admin sounds interesting too. with the ResourceBundle, this could reduce the admin to a bit of js configuration...

...together with that, it reminded me of a project I was working on, but which got slightly abandoned. Microsoft published the [OData](http://www.odata.org/) spec, which is a spec on top of rest. As they describe it themselves: 

> An open protocol to allow the creation and consumption of queryable and interoperable RESTful APIs in a simple and standard way.

Basically OData describes a way to do REST with a very well specified metadata format. It's intended for publishing an API from which a client can infer the entire model, without needing any prior knowledge. It's interesting here because you could infer an entire default admin interface just from the metadata: forms with the correct fields for dates, long text, numerical etc., parent-child relationships between models, basically everything (or at least everything that .NET's Entity Framework needs to do its magic, and it can do a bit of magic).

There are quite a few OData client libraries for javascript that can help with the frontend part (http://www.odata.org/libraries/). The problem is that there are currently no good PHP libraries for building OData API's. And that's why it reminded me of that old project, because that was exactly what I was working on. I basically already built a library for defining the metadata model (https://github.com/RSSchermer/EntityDataModel/tree/master/src/Rolab/EntityDataModel). 
What would still need to be build:

- An OData (de)serialization library for serializing the models and producing the metadata document.
- A symfony bundle integrating the EntityDataModel definition, the serialization, the routing and the controllers.
- A js frontend build on top of an existing OData client library (and probably angular, ember or react?).

Providing an admin interface for a document would then only amount to adding a few annotations (annotate field types and relationships and... done).

It will still be a humongous amount of work to build this admin framework, but it would probably be the most convenient admin framework ever.

**Comment by dbu** [comment]
@rande make sure to have a look at https://github.com/marmelab/ng-admin - maybe you can collaborate with them to build a great admin tool? imho there are currently too many competing admin solutions that are either immature or lack in documentation and developer experience. focussing on one project per approach could do a lot to help here.

@RSSchermer that odata thing reminds me a bit of what we do with CreateBundle. create.js lacks the components to have different data types, but uses this approach of annotations and then inferring the editing from that - but it does so right in the rendered template, to have seamless, true frontendediting. i think there are several parts to this question:

* Tool for the backend API
* Tool to do the actual editing
* Tool to configure the actual editing - this is the real challenge. 

the OData approach probably will have the problem that a lot of magic is involved when creating editing. this can make it harder to customize. on the other hand, the developer should not have to write lots of trivial boilerplate for when default is actually right...

**Comment by RSSchermer** [comment]
> the OData approach probably will have the problem that a lot of magic is involved when creating editing. this can make it harder to customize. on the other hand, the developer should not have to write lots of trivial boilerplate for when default is actually right...

I think you can make something highly customizable, but provide sensible defaults for all the options.

> Tool to configure the actual editing - this is the real challenge.

I think this is no different for any approach that does admin through a REST API. I think the most sensible thing to do is configuration in javascript in one central file. You couldn't really do configuration on a 'per document' basis, as you do with sonata Admin classes at the moment. However, I don't think the CMF bundles would have to be concerned with admin specific things anymore, they'd only have to configure how to expose their documents through the API. The big advantage of this that the bundles are not tied to any specific admin implementation, but that you can provide a 'SimpleCMS' example bundle that has an admin interface. You could also reuse the api for other things, like mobile integration. Personally I think the 'admin through a REST API' idea is really attractive.

I also think that it would be attractive to use an existing format for this API instead of coming up with a custom format. OData is the best candidate I know. The only 2 others I know of are:

- Linked Data Platform: W3 spec, related to RDF. It's very web 3.0, good at linking between multiple endpoints. The resource must an RDF resource represented as turtle though, which is a pain the backside imo.
- jsonapi.org: I like this spec for SPA development. It's good for building applications where you already know what the schema of the API is. It's not very good at discoverability and metadata though.

With OData you can provide a json api. It's pretty straightforward to parse OData json as just normal json payloads without knowing anything about OData. If you care about the metadata though, it's there and you could do things with it like inferring a lot of defaults for an admin interface. Perhaps someone else knows of an even better candidate though.

**Comment by dantleech** [comment]
Note that we are currently developing a REST API (or at least a resource gateway API): [https://github.com/symfony-cmf/ResourceRestBundle](ResourceRestBundle). This API will expose abstract resources (e.g. ORM entities, ODM documents, filesystem files) and metadata on the resources, e.g. links (edit, delete, create, other REST endpoints).

**Comment by lsmith77** [comment]
IMHO the oData approach could be nice but I think it would be better to take an intermediate step with a cleaned up implementation on top of RDFa/JSON-LD and/or JSON API spec. Once we have that working, it should be a smaller and therefore more realistic step to explore such a highly generic approach with oData.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
