### ISSUE TITLE
A better way of importing JS resources for tree input

### ISSUE THREAD

**Issue by wouterj** [sonata-project/SonataDoctrinePhpcrAdminBundle#327]
Currently, the JS and CSS files required for the JS input are loaded at the field itself. This doesn't result in a very great page rendering:
1. The page renders until the tree field
2. It then waits to load all the files and execute the javascript
3. After that happend, the rest of the page is rendered

It also means that including the tree field 3 times would lead to loading all assets 3 times.

**Comment by ElectricMaxxx** [comment]
So we should add the js/css files to the admin-pool when the tree-bundle is active? So sonata would add it.

**Comment by dbu** [comment]
i guess ideally "something" combines the js / css files in sonata and we just always deliver the tree things. no point in trying to conditionally include only once when tree is used.

**Comment by ElectricMaxxx** [comment]
Is that still relevant? Especiall when tree-browser-bundle is used?

**Comment by dbu** [comment]
afaik the tree bundle combines js resources into one file. right @wouterj ?

**Comment by wouterj** [comment]
Yeah, but they are still loaded half-way through the page and they are still loaded 3 times if the tree is rendered 3 times.

**Comment by ElectricMaxxx** [comment]
@wouterj @pulzarraider What would be a nice point to register assets to admin poo? 
- BundleExtension?
- Controller?
- AdminClass?

**Comment by ElectricMaxxx** [comment]
I think we should devide that into two parts.

The `treebrowser-bundle` should be able to work standalone, so should use its view template to insert the js/css files, but with the usage of sonata we would add the js/css files to the admin pool and should trigger treebundle not to use the view template.

**Comment by wouterj** [comment]
I proposed a way to fix this in https://github.com/symfony-cmf/tree-browser-bundle/pull/137

**Comment by ElectricMaxxx** [comment]
Doing so, means just handling `jquery` and `jquery-ui`  would mean, i have to do nothing then removing the script template inclusion as sonata will load them by default, right?

**Comment by ElectricMaxxx** [comment]
so as symfony-cmf/tree-browser-bundle#137 was merged, did we solve this one too?

**Comment by wouterj** [comment]
This is mostly solved now. The issue consisted of 2 parts:

 1. Very important: Load only once -> Fixed
 2. Very not important: Load somewhere in the head instead of halfway through the body
