### ISSUE TITLE
Version that works with admin-bundle latest stable (2.3.2)

### ISSUE THREAD

**Issue by jmeyo** [sonata-project/SonataDoctrinePhpcrAdminBundle#331]
I'm struggling a bit to fix my composer in order to use that doctrine odm integration.
All stable release of SonataDoctrinePhpcrAdminBundle require sonata admin-bundle <=2.3.0, and latest stable version from admin-bundle is 2.3.2 (which contains fix I'm upgrading for).
Can you point me where you explain why you are sticked to release 2.3.0 ?
I had a look to #302 but doesn't explain why that dependency is that strict.

**Comment by dbu** [comment]
sonata-admin is breaking BC between minor versions. to support 2.4, we need to change things to be compatible.

you can ask composer for the phpcr admin 2.0@dev to get a version that asks for admin 2.4. but this really is still dev and not ready to use.

if you want to have a look and can help on the open PRs / create new PRs for phpcr admin 2.0, we appreciate any help.

**Comment by jmeyo** [comment]
Indeed, I had often troubles with sonata admin, and always struggling to find the correct info. I would love to help indeed, I will have a look, but I need to deliver. I added my own fork with a less restrictive constraints on admin bundle, in order to use the last minor version of sonata admin. 
Asking for 2.4 version didn't work as I wanted to setup the full cmf stack also (had some issue with the tree-browser-bundle).
