### ISSUE TITLE
Sortable not working

### ISSUE THREAD

**Issue by danielantelo** [sonata-project/SonataDoctrinePhpcrAdminBundle#332]
So i have a sonata_type_collection working in my symfony cmf project, it creates, updates and removes child documents correctly. 

I now want to enable sortable, but when i save with the sortable flag enabled i get "NodeName property "nodeName" may not be empty in document of class..."

Is this a known issue? or am i doing something wrong.

```
->add(
     'someChidlren',
     'sonata_type_collection',
     array(
          'label'    => false,
          'by_reference'   => false,
          'cascade_validation' => true,
     ),
     array(
          'admin_code' => 'admin_reference_here',
          'edit'   => 'inline',
          'inline' => 'table',
           'sortable'  => 'position',
     )
)
```

**Comment by lsmith77** [comment]
might also need to be fixed in 1.2

**Comment by ElectricMaxxx** [comment]
@lsmith77 @dbu do we have an example where i could test that in sandbox? Or an example where i can implement an examaple in sandbox.

**Comment by dbu** [comment]
i found no place where we would use sonata_type_collection in the sandbox (only found the definition of the type, grepping through the code). it would make sense to use it on the container block admin. (i think we had it on the slideshow block for individual slides, but thats media bundle)

**Comment by ElectricMaxxx** [comment]
yea but with the deprecation of meda bundle we should temporary remove
the complete image/slideshow blocks, but indeet i will try to get an
example that way.

**Comment by ElectricMaxxx** [comment]
```
        if ('doctrine_phpcr' != $options['sonata_field_description']->getAdmin()->getManagerType() || !$options['sonata_field_description']->getOption('sortable')) {
            return;
        }
```

sounds like the eventlistener to fill up data isn't registered for `sortable`

**Comment by dbu** [comment]
i removed the milestone completely. if nobody plans on working on it, there is no point in having it in a milestone.
