### ISSUE TITLE
PhpcrOdmTree compatibility with Symfony 2.7

### ISSUE THREAD

**Issue by wcluijt** [sonata-project/SonataDoctrinePhpcrAdminBundle#335]
With Symfony 2.7, the `templating.helper.assets` service now uses the `Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper` class rather than the deprecated `Symfony\Component\Templating\Helper\CoreAssetsHelper` class.

Since this service is passed as an argument of the `sonata.admin.doctrine_phpcr.phpcr_odm_tree` service (https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Resources/config/tree.xml#L24), the related PhpcrOdmTree constructor argument type hint (https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Tree/PhpcrOdmTree.php#L117) should be removed and additional logic added to check if the input is an instance of one of these classes.

Also, with the new `assets.packages` service in Symfony 2.7, it's possible that an instance of `Symfony\Component\Asset\Packages` or `Symfony\Component\Asset\Package` could be passed in to the constructor as well.  Each of these classes has a getUrl() method which appears to be the only requirement of the PhpcrOdmTree class.

**Comment by dbu** [comment]
thanks for investigating these issues @wcluijt 

for the upcoming 2.0 of this bundle, @WouterJ is refactoring a lot of the setup. i expect some of the issues to be irrelevant for that.

@wcluijt if you could do a pull request with those changes (remove typehint, add instanceof checks) against the 1.2 branch of this bundle, that would be great!

**Comment by WouterJ** [comment]
@dbu can you maybe create a list of issues related to the tree browser. They seem to be spread across many repositories, many of them not followed by me.

I expect most of them to be no longer valid, as both frontend and backend are completely revisited. So we have to go through all of them when tree browser 2.0 is in beta/rc

**Comment by wcluijt** [comment]
I created the related pull request https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/337.

**Comment by lsmith77** [comment]
so this can be closed?

**Comment by wouterj** [comment]
*This issue can be closed, the fixing PR #337 is merged in 1.x and 2.0 doesn't have the `PhpcrOdmTree` class anymore.*
