### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by marvoh** [sonata-project/SonataDoctrinePhpcrAdminBundle#353]
Hi,

I am unable to install this package with the command below:

     composer require sonata-project/doctrine-orm-admin-bundle

However, it's not working and I get the error below

    Problem 1
    - The requested package symfony/symfony == 3.0.1.0 could not be found.

Anyone who can help?

**Comment by lsmith77** [comment]
I think you opened this ticket on the wrong repository .. this is for the PHPCR ODM layer and your issue seems to be with the ORM layer .. ie. https://github.com/sonata-project/SonataDoctrineORMAdminBundle

**Comment by dbu** [comment]
as lukas said, this is not the orm admin repository.

but your error looks as if you have a requirement for symfony 3.0.1.0 in your composer.json. try to composer update without requiring the admin and see if that even works. check if your composer.json mentions a version 3.0.1.0 and fix that to 3.0.* or whatever makes sense for you.
