### ISSUE TITLE
Symfony 3 support

### ISSUE THREAD

**Issue by billsworld** [sonata-project/SonataDoctrinePhpcrAdminBundle#361]
When trying to install Symfony 3 alongside this bundle I get the following

`sonata-project/doctrine-phpcr-admin-bundle 1.2.4 requires symfony/property-access ~2.2 -> satisfiable by symfony/symfony[v2.8.2, 2.2.x-dev...`

Is support for v3 planned? What can I do to help?

**Comment by dbu** [comment]
some of the upgrade work is done in #348

you could try to start from the work @WouterJ did. note that we think its too much hassle to support 2.3 and 3.0 at the same time, so we want to increase the minimum version requirement to symfony 2.7 or 2.8.

**Comment by billsworld** [comment]
@WouterJ I am not too sure where to go based on your changes. Let me know if there is something I can do to help get ready for Symfony 3

**Comment by Soullivaneuh** [comment]
> so we want to increase the minimum version requirement to symfony 2.7 or 2.8.

See also https://github.com/sonata-project/dev-kit/issues/51

**Comment by wouterj** [comment]
*This issue can be closed, Symfony 3.0 is supported by 2.x-dev*
