### ISSUE TITLE
Update composer.json (sonata-admin-bundle 2.4 does not exist)

### ISSUE THREAD

**Issue by INHack20** [sonata-project/SonataDoctrinePhpcrAdminBundle#368]
sonata-project/admin-bundle: ~2.4 is not longer avalable, now is sonata-project/admin-bundle: 3.x-dev please update dependencies.

Thansk.

**Comment by Soullivaneuh** [comment]
This is WIP, see https://github.com/sonata-project/SonataAdminBundle/issues/3731.

If you want to solve it yourself, please see https://github.com/sonata-project/SonataAdminBundle/issues/3731#issuecomment-212636270

**Comment by dbu** [comment]
the master branch of phpcr admin is WIP as well and referenced the 2.4 admin. i just changed that to 3.0 now.
