### ISSUE TITLE
tree-browser and resource-rest stable ETA

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataDoctrinePhpcrAdminBundle#373]
Have you an ETA for `symfony-cmf/tree-browser-bundle` and `symfony-cmf/resource-rest-bundle` stable release?

I would like to push a new major for sonata-admin 3.0 support and deprecate the 1.x one but those bundle are already required with unstables versions.

Thanks.

cc dbu @lsmith77 @dantleech @sjopet @rmsint

**Comment by dbu** [comment]
@WouterJ is most active with the tree browser. can you please check the milestones and make sure the relevant issues that need to be done are there? and maybe label things as nicetohave that we could also do without?

**Comment by WouterJ** [comment]
The biggest "problem" is Puli. It has to be released stable in order to mark ResourceRestbundle stable.

**Comment by WouterJ** [comment]
ping @webmozart, what are the plans to release Puli 1.0 stable?

**Comment by iBasit** [comment]
+1 

it will really help to get basic stable versions for all the chained bundles

**Comment by Soullivaneuh** [comment]
I will start dev-kit integration.

1.x will be the stable branch for now, but not compatible with the new ecosystem.

When all dependencies will be stable on master, we will release a 2.x tag and deprecate the 1.x.

**Comment by dbu** [comment]
thanks!

**Comment by wouterj** [comment]
Fyi, we're now about to release RC's of CMF 2.0. Expect a stable release this month.
