### ISSUE TITLE
Route '_cmf_resource' not found

### ISSUE THREAD

**Issue by iBasit** [sonata-project/SonataDoctrinePhpcrAdminBundle#374]
After installing CMF and all the requirements. I'm getting following error on the admin area, I have went thorough all the documenations again and again, and I'm not sure how to resolve this.

Is there routing file we need to include or bundle to remove his issue? 

> An exception has been thrown during the rendering of a template ("None of the chained routers were able to generate route: Route '_cmf_resource' not found") in SonataDoctrinePHPCRAdminBundle:Tree:tree.html.twig at line 34.

**Comment by WouterJ** [comment]
This means you're installing 2.0-DEV of this bundle. Please use stable versions (With Symfony 2.8) if you want to follow the documentation.

To fix this, enable the CmfResourceBundle and CmfResourceRestBundle in the AppKernel and include the CmfResourceRestBundle routing's in `app/config/routing.yml` like this: https://github.com/symfony-cmf/cmf-sandbox/pull/329/files#diff-c0e77287aafd0eb4d2a33f1980321a3bR52 Also keep in mind to configure the bundles like this: https://github.com/symfony-cmf/cmf-sandbox/pull/329/files#diff-bf0e70bcef1a5d5b2f87289220a51108R121

**Comment by wouterj** [comment]
*This issue can be closed, as it's a user support question that has been answered.*
