### ISSUE TITLE
Sync master with 1.2

### ISSUE THREAD

**Issue by wouterj** [sonata-project/SonataDoctrinePhpcrAdminBundle#376]
Some bugs where fixed in 1.2, including this major one: #360 

As master isn't in sync with 1.2 (for a long time), these bugs aren't fixed in master and breaking code at the moment.

**Comment by dbu** [comment]
hrm. i don't get it. git merge origin/1.x from branch master says nothing to do.

when i look at the git history of master, the exact commit id (with the change i see here on github) from #360 is in the history. when i git blame the file, the line with the wrong class name has another commit id. but in the git history, that other commit with the wrong class name is older than the one that would fix it. i have no idea how that is even possible to do. if there was a wrong conflict resolution, we should see a merge conflict commit for that line.

there are of course tons of other changes to the code, so its hard to see what else might be missing. @Soullivaneuh do you have an idea what could be on here?

**Comment by Soullivaneuh** [comment]
@dbu I did the first merge here after `1.x` creation. https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/commit/8576eaf2a3d00608bf978307e7938ccbcb1c4591

I didn't notice any conflicts as I remember.

Maybe skipped changes on older merges?

Anyway, I don't see how to fix it with ease... maybe we should cherry-pick them on PR for master.

> Some bugs where fixed in 1.2, including this major one: #360

@WouterJ Did you find another notable fixed bug that are not on master?

**Comment by dbu** [comment]
@WouterJ so it seems we have a git mistery here :-( did you notice
anything else that is missing? or have any idea how we can recover the
situation? otherwise i am just going to cherry-pick

**Comment by OskarStark** [comment]
i just checked the article with a glympse, but maybe it can help or make it a little bit more clear:
http://stackoverflow.com/questions/13468027/the-mystery-of-the-missing-commit-across-merges

**Comment by greg0ire** [comment]
> I didn't notice any conflicts as I remember.

Tried it myself just now and there are a lot of conflicts : 

```
git checkout master
git reset --hard 62ab6e0
git checkout 1.x
git reset --hard e997bd0
git merge 1.x    
Auto-merging composer.json
CONFLICT (content): Merge conflict in composer.json
CONFLICT (modify/delete): Tree/PhpcrOdmTree.php deleted in HEAD and modified in 1.x. Version 1.x of Tree/PhpcrOdmTree.php left in tree.
Auto-merging Resources/views/Block/tree.html.twig
CONFLICT (content): Merge conflict in Resources/views/Block/tree.html.twig
Auto-merging CHANGELOG.md
CONFLICT (content): Merge conflict in CHANGELOG.md
Auto-merging Builder/FormContractor.php
CONFLICT (content): Merge conflict in Builder/FormContractor.php
Auto-merging Block/TreeBlockService.php
CONFLICT (content): Merge conflict in Block/TreeBlockService.php
Auto-merging .travis.yml
CONFLICT (content): Merge conflict in .travis.yml
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by Soullivaneuh** [comment]
I said "as I remember". Hard to say after refactoring 30 github repositories. :stuck_out_tongue: 

Maybe I did a wrong resolving somewhere...

@greg0ire Any suggestion to fix this?

**Comment by greg0ire** [comment]
I have to check if the diff is about precisely those bugfixes, but it seems a bit unlikely.

**Comment by greg0ire** [comment]
> I have to check if the diff is about precisely those bugfixes, but it seems a bit unlikely.

Oh but the code for #360 is part of the diff, so it is likely after all.

**Comment by greg0ire** [comment]
@greg0ire Any suggestion to fix this?

I'd say look at the diff and carefully cherry-pick the commits that introduce the good changes

**Comment by WouterJ** [comment]
> I'd say look at the diff and carefully cherry-pick the commits that introduce the good changes

Looking at the diff, only the commit referenced in this issue needs to be cherry-picked.

Good detective work btw! 🔍

**Comment by greg0ire** [comment]
Thanks :blush:

**Comment by Soullivaneuh** [comment]
@WouterJ When you have a git problem, always call @greg0ire! :stuck_out_tongue:

**Comment by dbu** [comment]
created #393. how did you decide to set the two branches to the commits in your example?

i am still puzzled how `git blame` can say that the line was last changed in december, but git log does have the newer commit (and coming more recently than the one from december) that would fix that line... and no other things listened by `git log Builder/FormContractor.php` that would revert the change.

**Comment by WouterJ** [comment]
> i am still puzzled how git blame can say that the line was last changed in december, but git log does have the newer commit (and coming more recently than the one from december) that would fix that line... and no other things listened by git log Builder/FormContractor.php that would revert the change.

If you have merge conflicts and reset it to the HEAD change (and not the other change), nothing is changed and git blame can't show anything.

**Comment by greg0ire** [comment]
> how did you decide to set the two branches to the commits in your example?

Because @Soullivaneuh talked about this one in particular, and because the git graph shows there was a big difference in number of commits between the branches before the merge, and likeliness of faulty merges grows higher the bigger the merge is.

As per the log, it's indeed weird that the change from the merge commit doesn't appear as soon as you use a filename

**Comment by greg0ire** [comment]
> As per the log, it's indeed weird that the change from the merge commit doesn't appear as soon as you use a filename

> If you have merge conflicts and reset it to the HEAD change (and not the other change), nothing is changed and git blame can't show anything.

That's the right explanation, thanks @WouterJ !

**Comment by wouterj** [comment]
Closing, as it's fixed by https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/393
