### ISSUE TITLE
tree default click behaviour

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#383]
A left click on items in the tree selects the item but does not edit and shows no options. IMHO it should either keep the old behaviour of opening the edit view for this item, or it should open the dropdown menu. As is, its quite confusing. as nothing happens.

can be seen [here](http://admin:admin@sandbox.cmf.symfony.com/en/admin/dashboard).

**Comment by OskarStark** [comment]
@dbu i updated the link to include the basic auth credentials

**Comment by OskarStark** [comment]
Looks like github has some problems to render such links

**Comment by OskarStark** [comment]
> IMHO it should either keep the old behaviour of opening the edit view for this item

👍

**Comment by Soullivaneuh** [comment]
> Looks like github has some problems to render such links

And like I did?

**Comment by wouterj** [comment]
*This issue is now fixed: https://github.com/symfony-cmf/tree-browser-bundle/issues/132*
