### ISSUE TITLE
Wrong mapping type used in form_admin_fields.html.twig

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/SonataDoctrinePhpcrAdminBundle#389]
## Subject

Hi,
I'm currently working on moving the CRUD association fields templates back to the admin bundle, as mentioned [here](https://github.com/sonata-project/SonataAdminBundle/pull/3647#issuecomment-220129380), and encountered the following issue.

Given the following classes (irrelevant fields omitted for brevity):

``` php
namespace AppBundle\Document {
  /** @PHPCR\Document(referenceable=true) */
  class Person {}
  /** @PHPCR\Document() */
  class Post {
    /** @PHPCR\ReferenceOne(targetDocument="Person") */
    private $author;
  }
}
namespace AppBundle\Admin {
  class PersonAdmin {}
  class PostAdmin {
    public function configureFormFields($formMapper) {
      $formMapper->add('author', 'sonata_type_admin');
    }
  }
}
```

The embedded `PersonAdmin` does not show up in the `PostAdmin` edit form.
The mapping type between Post and Person is `ClassMetadata::MANY_TO_ONE` which has a numerical value of 4.
However the [sonata_type_admin block](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/1.x/Resources/views/Form/form_admin_fields.html.twig#L120) considers `4` as being a one-to-many relationship.
Furthermore, it checks agains other numerical values which seem to correspond to the mapping constants of the doctrine ORM (not phpcr-odm!).

To me the widget's block should read like:

``` twig
{% block sonata_type_admin_widget %}
  {% set _mapping_type = sonata_admin.field_description.mappingType|default(null) %}

  {% if (
    _mapping_type is constant('Doctrine\\ODM\\PHPCR\\Mapping\\ClassMetadata::MANY_TO_ONE'
    or _mapping_type == 'child'
  ) %}
      {{ block('sonata_admin_phpcr_one_to_one_widget') }}
  {% else %}
    The admin widget supports only TO_ONE relationships
  {% endif %}
{% endblock %}
```

So I would like to know:
- Am I completely wrong ?
- Is the code completely wrong ? :stuck_out_tongue_winking_eye:
- Where do these numerical values come from ?
- How do the 'child', 'children', 'parent' and 'referrers' mapping types relate to the "standard" ONE_TO_ONE, ONE_TO_MANY, etc... types ?

**Comment by dbu** [comment]
it is well possible that something got mixed up while porting code from orm admin to phpcr admin.

phpcr does not have the classical relational view on a database, but is organized as a tree. you have the following things:

* child => one to one
* children => one to many
* parent => many to one
* reference => one to one
* reference(multivalue=true) => one to many
* referrers => many to one

references are cross-links that do not follow the tree hierarchy. there can be more than one document that references the same document. but as its always the property of one document that holds the references to other documents, i think the visual representation is still one to many.

does that help?

**Comment by ju1ius** [comment]
> does that help?

Given I used phpcr for the first time yesterday, that's an enlightenment ! :raised_hands:
Thanks very much @dbu !

**Comment by dbu** [comment]
you are welcome. don't hesitate to ask if you need further help. i am
very glad you are working on unifying this. whatever the underlying
concepts, at the end of the day the admin interface for a document with
some relations always looks very similar, so having the same code for
all of that makes sense.

**Comment by ju1ius** [comment]
So if I get it right, `ClassMetadata::MANY_TO_ONE` and `ClassMetadata::MANY_TO_MANY`
are used by the ODM to distinguish `reference` and `reference(multivalue=true)` ?

**Comment by dbu** [comment]
i am not entirely sure what we currently do or if its correct in every
instance :-)

in terms of models, lets say we have class A and B. A::ref is a
reference to any single instance of B. that would be the |reference|
case. each instance of A could point to the same B. so i guess yes,
MANY_TO_ONE. and with multivalue, many A could point to many B. i think
that makes sense to consider a MANY_TO_MANY relation.

with that logic, a referrers mapping would be MANY_TO_MANY. referrer is
the inverse of reference: a list of all documents that point to a
document. by nature, this can be multiple documents, and several
instance can be referenced, so its MANY_TO_MANY as well.

when interacting with the model, you don't really need to distinguish
between referrers and reference many - its both a collection of
documents. the difference is in the storage system.

**Comment by jordisala1991** [comment]
templates are centralized on admin bundle now, so this specific issue shouldnt be a problem now
