### ISSUE TITLE
Service defintion for missing filter

### ISSUE THREAD

**Issue by ElectricMaxxx** [sonata-project/SonataDoctrinePhpcrAdminBundle#425]
It seems as we miss a filter or forgot to remove the service definition:

```xml
        <service id="sonata.admin.doctrine_phpcr.filter.type.model" class="Sonata\DoctrinePHPCRAdminBundle\Filter\ModelFilter">
            <tag name="sonata.admin.filter.type" alias="doctrine_phpcr_model"/>
        </service>
```

I can't find the filter, and my IDE too.

**Comment by dbu** [comment]
yep, that looks unusable. maybe a copy-paste mistake. i would say we should remove it in master only, to avoid surprises.
