### ISSUE TITLE
Oudated docs

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataDoctrinePhpcrAdminBundle#427]
The docs still refer to the old google groups: https://sonata-project.org/bundles/doctrine-phpcr-admin/1-x/doc/index.html

We use slack and stackoverflow now.

**Comment by dbu** [comment]
the orm doc also has those links. when we merge #525 i can do a similar PR on the other projects.

i considered adding slack / stackoverflow links, but i think we should rather have a general "Help" menu point in the main website if we want to advertise those channels.
