### ISSUE TITLE
Configuration for treebrowser options

### ISSUE THREAD

**Issue by ElectricMaxxx** [sonata-project/SonataDoctrinePhpcrAdminBundle#441]
## Subjecton

We have some configuration that isn't used any more and we do have new options on the new treebrowser which should be definded as bundle configuration again.

## List of existing configurations

- document_tree_options.confirm_move
- document_tree_options.precise_children 
- document_tree_config. * (no usage anymore atm)
- document_tree_defaults (is more a routing default configuration)

### New options on treebrowser

- sortableBy
- drag & drop
-- enabled
-- reorder

**Comment by dbu** [comment]
how does this relate to #435 ? did you there add the feature but we want to add configuration options to disable that feature? would that be for the tree on the dashboard or other trees?

and i guess we simply want to remove all config that is no longer used anywhere, and add notes to the changelog.

**Comment by ElectricMaxxx** [comment]
It was a question how to handle the configuration at all. -------- Originalnachricht --------Betreff: Re: [sonata-project/SonataDoctrinePhpcrAdminBundle] Configuration for treebrowser options (#441)Von: David Buchmann An: sonata-project/SonataDoctrinePhpcrAdminBundle Cc: Maximilian Berghoff ,Assign how does this relate to #435 ? did you there add the feature but we want to add configuration options to disable that feature? would that be for the tree on the dashboard or other trees?
and i guess we simply want to remove all config that is no longer used anywhere, and add notes to the changelog.

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sonata-project/SonataDoctrinePhpcrAdminBundle","title":"sonata-project/SonataDoctrinePhpcrAdminBundle","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dbu in #441: how does this relate to #435 ? did you there add the feature but we want to add configuration options to disable that feature? would that be for the tree on the dashboard or other trees?\r\n\r\nand i guess we simply want to remove all config that is no longer used anywhere, and add notes to the changelog."}],"action":{"name":"View Issue","url":"https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/issues/441#issuecomment-312274859"}}}

**Comment by ElectricMaxxx** [comment]
solved by #453
