### ISSUE TITLE
Improve controller methods

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#537]
## Feature Request

Follow up of #535, the controllers should not use the `Action` suffix anymore according to https://symfony.com/doc/current/best_practices/controllers.html#controller-action-naming . to avoid a BC break, first add methods without the suffix, make the suffix methods call those new methods and issue a deprecation warning.

Removing the deprecated methods can only be done in a new major version.

**Comment by core23** [comment]
Why not using the Action pattern by replacing the huge Contollers with simple `*Action` classes?

**Comment by dbu** [comment]
or that. i do not plan to work on this, it just came up in #535 and i wanted to record the issue.

**Comment by greg0ire** [comment]
Just so you know, we are moving all the other bundles towards invokable controllers as a service, with constructor injection.

**Comment by dbu** [comment]
i think this is mostly cosmetics, not important compared to all the other things.
