### ISSUE TITLE
control allowed target documents for parent selection

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#61]
follow-up of #23

**Comment by dbu** [comment]
@WouterJ says: This can be integrated in the new Sonata admin enhancer in the ResourceRestBundle. In fact, the complete tree backend from the SonataDoctrinePhpcrAdminBundle is going to be removed and replaced with ResourceRestBundle. This feature is not yet integrated in the Sonata admin enhancer.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
