### ISSUE TITLE
document TreeManagerType

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataDoctrinePhpcrAdminBundle#95]
https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/89
https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/91

and also explain how to edit things in an ajax overlay

/cc @elhornair

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists. @dbu
